spring:
  application:
    name: review
  profiles:
    active: local
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

server:
  port: 8087
  servlet:
    context-path: /api

services:
  product:
    baseUrl: http://${PRODUCT_HOST:localhost}:8085/api/v1/product

logging:
  level:
    root: INFO
    "[cl.gestion.ventas.review]": DEBUG

  file:
    name: logs/review-service.log

jwt:
  secret: 46238dr3r67246y423784rt687342rys832q47rt
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
allowed:
  origin: ${ALLOWED_ORIGIN:http://localhost:8080}
