services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - networksita

  ms-auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - networksita
    healthcheck:
      test: ["CMD", "wget","--quiet","--tries=1","--spider","http://localhost:8090/api/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

networks:
  networksita:
    driver: bridge