server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:true}

logging:
  level:
    root: INFO
    "[org.springframework.cloud.gateway]": DEBUG
  file:
    name: logs/api-gateway.log

springdoc:
  swagger-ui:
    urls:
      - name: Autenticación y Usuarios
        url: /auth/api/v3/api-docs
      - name: Carrito
        url: /cart/api/v3/api-docs
      - name: Inventorio
        url: /inventory/api/v3/api-docs
      - name: Orden
        url: /order/api/v3/api-docs
      - name: Producto
        url: /product/api/v3/api-docs
      - name: Categoria
        url: /category/api/v3/api-docs
      - name: Notificación
        url: /notification/api/v3/api-docs
      - name: Pago
        url: /payment/api/v3/api-docs
      - name: Reseña
        url: /review/api/v3/api-docs
      - name: Envío
        url: /shipping/api/v3/api-docs
