spring.application.name=shipping

#Configuración de base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/shipping_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#Configuración de Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

#Configuración de JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

#Configuración de servidor
server.port=8081
server.servlet.context-path=/api

#Configuración de logs
logging.level.root=INFO
logging.level.cl.gestion.ventas.shipping=DEBUG
logging.file.name=logs/shipment-service.log

#Configuración de JWT
jwt.secret=46238dr3r67246y423784rt687342rys832q47rt

#Servicios externos