# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: auth
  profiles:
    active: local 
server:
  port: 8090
  servlet:
    context-path: /api
logging:
  level:
    root: INFO
    cl:
      gestion:
        ventas:
          auth: DEBUG
  file:
    name: logs/users-service.log
jwt:
  secret: 46238dr3r67246y423784rt687342rys832q47rt
  expiration: 3600000
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
