CREATE TABLE reviews (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    user_name VARCHAR(20) NOT NULL,
    rating INT NOT NULL,
    comment VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);