spring:

    application:
        name: category

    datasource:
        url: jdbc:mysql://localhost:3306/category_db
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver

    flyway:
        enabled: true
        locations: classpath:db/migrations
        baseline-on-migrate: true
    
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        open-in-view: false
    
server:
    port: 8086
    servlet:
        context-path: /api

logging:
  level:
    "[org.springframework]": INFO
    "[com.product]": DEBUG

  file:
    name: logs/category-service.log

jwt:
    secret: 46238dr3r67246y423784rt687342rys832q47rt